config/routes.rb
Vedavaagproject::Application.routes.draw do
  resources :states

  resources :customers

  resources :current_projects

end

app/models/current_project.rb
class CurrentProject < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/current_projects_controller.rb
class CurrentProjectsController < ApplicationController
  before_action :set_current_project, only: [:show, :edit, :update, :destroy]

  # GET /current_projects
  # GET /current_projects.json
  def index
    @current_projects = CurrentProject.all
  end

  # GET /current_projects/1
  # GET /current_projects/1.json
  def show
  end

  # GET /current_projects/new
  def new
    @current_project = CurrentProject.new
  end

  # GET /current_projects/1/edit
  def edit
  end

  # POST /current_projects
  # POST /current_projects.json
  def create
    @current_project = CurrentProject.new(current_project_params)

    respond_to do |format|
      if @current_project.save
        format.html { redirect_to @current_project, notice: 'Current project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @current_project }
      else
        format.html { render action: 'new' }
        format.json { render json: @current_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /current_projects/1
  # PATCH/PUT /current_projects/1.json
  def update
    respond_to do |format|
      if @current_project.update(current_project_params)
        format.html { redirect_to @current_project, notice: 'Current project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @current_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /current_projects/1
  # DELETE /current_projects/1.json
  def destroy
    @current_project.destroy
    respond_to do |format|
      format.html { redirect_to current_projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_current_project
      @current_project = CurrentProject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def current_project_params
      params[:current_project]
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @customer }
      else
        format.html { render action: 'new' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params[:customer]
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render action: 'show', status: :created, location: @state }
      else
        format.html { render action: 'new' }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params[:state]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/current_projects_helper.rb
module CurrentProjectsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/current_projects/_form.html.erb
<%= form_for(@current_project) do |f| %>
  <% if @current_project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@current_project.errors.count, "error") %> prohibited this current_project from being saved:</h2>

      <ul>
      <% @current_project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/current_projects/edit.html.erb
<h1>Editing current_project</h1>

<%= render 'form' %>

<%= link_to 'Show', @current_project %> |
<%= link_to 'Back', current_projects_path %>

app/views/current_projects/index.html.erb
<h1>Listing current_projects</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @current_projects.each do |current_project| %>
      <tr>
        <td><%= link_to 'Show', current_project %></td>
        <td><%= link_to 'Edit', edit_current_project_path(current_project) %></td>
        <td><%= link_to 'Destroy', current_project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Current project', new_current_project_path %>

app/views/current_projects/new.html.erb
<h1>New current_project</h1>

<%= render 'form' %>

<%= link_to 'Back', current_projects_path %>

app/views/current_projects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_current_project_path(@current_project) %> |
<%= link_to 'Back', current_projects_path %>

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vedavaagproject</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/states/_form.html.erb
<%= form_for(@state) do |f| %>
  <% if @state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% @state.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing state</h1>

<%= render 'form' %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<h1>Listing states</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= link_to 'Show', state %></td>
        <td><%= link_to 'Edit', edit_state_path(state) %></td>
        <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New State', new_state_path %>

app/views/states/new.html.erb
<h1>New state</h1>

<%= render 'form' %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>